In [2]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import classification_report

In [4]:
sheet = pd.read_csv("Iris.csv")
sheet

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
sheet_x=sheet.iloc[:,[1,4]].values

In [6]:
sheet_y=sheet.iloc[:,5].values


In [7]:
x_train,x_test,y_train,y_test=train_test_split(sheet_x,sheet_y,test_size=0.2,random_state=2)


In [8]:
sc=StandardScaler()


In [9]:
x_train=sc.fit_transform(x_train)


In [10]:
GNB=GaussianNB()


In [11]:
GNB.fit(x_train,y_train)


GaussianNB()

In [12]:
y_pred=GNB.predict(x_test)


In [13]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 0,  0, 14],
       [ 0,  0,  8],
       [ 0,  0,  8]], dtype=int64)

In [14]:
ac=accuracy_score(y_test,y_pred)
ac

0.26666666666666666

In [15]:
report=classification_report(y_test,y_pred)
print(report)

                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        14
Iris-versicolor       0.00      0.00      0.00         8
 Iris-virginica       0.27      1.00      0.42         8

       accuracy                           0.27        30
      macro avg       0.09      0.33      0.14        30
   weighted avg       0.07      0.27      0.11        30



C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
error=1-ac
error

0.7333333333333334

In [17]:
prec_score=precision_score(y_test,y_pred,average=None)
prec_score

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([0.        , 0.        , 0.26666667])

In [18]:
rec_score=recall_score(y_test,y_pred,average=None)
rec_score

array([0., 0., 1.])

In [ ]:
print("Accuracy Score :",ac)